#!/usr/bin/env bash
pwd=$(dirname "$(readlink -e "$0")")
mkdir -p ${pwd}/app/config/jwt
jwt_passphrase=${JWT_PASSPHRASE:-$(grep ''^JWT_PASSPHRASE='' ${pwd}/app/.env | cut -f 2 -d ''='')}
echo "$jwt_passphrase" | openssl genpkey -out ${pwd}/app/config/jwt/private.pem -pass stdin -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096
echo "$jwt_passphrase" | openssl pkey -in ${pwd}/app/config/jwt/private.pem -passin stdin -out ${pwd}/app/config/jwt/public.pem -pubout
